import React from "react";

export const AllProducts = [
    {
      id: 1,
      brand: "HIGHLANDER",
      name: "Men Printed Casual Shirt",
      price: 609,
      oldPrice: 3399,
      rating: 4.4,
      reviews: 1420,
      img: "/mnt/data/225bb058-7f0d-415f-8e1f-78aa90b1b1a9.png",
      category: "Shirts",
      size: "L",
    },
    {
      id: 2,
      brand: "BEWAKOOF",
      name: "Men Oversized Graphic Tee",
      price: 599,
      oldPrice: 1299,
      rating: 4.4,
      reviews: 1020,
      img: "https://images.pexels.com/photos/6311656/pexels-photo-6311656.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=800",
      category: "T-Shirts",
      size: "M",
    },
    {
      id: 3,
      brand: "AUIND",
      name: "Streetwear Boxy Tee",
      price: 699,
      oldPrice: 1499,
      rating: 4.1,
      reviews: 278,
      img: "https://images.pexels.com/photos/1701193/pexels-photo-1701193.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=800",
      category: "T-Shirts",
      size: "L",
    },
    {
      id: 4,
      brand: "CAMPUS SUTRA",
      name: "Slim Fit Cotton Shirt",
      price: 579,
      oldPrice: 2899,
      rating: 3.9,
      reviews: 147,
      img: "https://images.pexels.com/photos/428340/pexels-photo-428340.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=800",
      category: "Shirts",
      size: "M",
    },
    {
      id: 5,
      brand: "FUBAR",
      name: "Bomber Jacket",
      price: 1799,
      oldPrice: 2999,
      rating: 4.5,
      reviews: 450,
      img: "https://images.pexels.com/photos/1468378/pexels-photo-1468378.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=800",
      category: "Jackets",
      size: "XL",
    },
    {
      id: 6,
      brand: "HIGH&CO",
      name: "Soft Winter Hoodie",
      price: 1499,
      oldPrice: 2499,
      rating: 4.2,
      reviews: 310,
      img: "https://images.pexels.com/photos/6311393/pexels-photo-6311393.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=800",
      category: "Hoodies",
      size: "L",
    },
    {
      id: 7,
      brand: "BEWAKOOF",
      name: "Daily Casual Tee",
      price: 499,
      oldPrice: 899,
      rating: 4.0,
      reviews: 670,
      img: "https://images.pexels.com/photos/1143763/pexels-photo-1143763.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=800",
      category: "T-Shirts",
      size: "M",
    },
    {
      id: 8,
      brand: "FUBAR",
      name: "Slim Fit Trousers",
      price: 899,
      oldPrice: 1699,
      rating: 4.1,
      reviews: 210,
      img: "https://images.pexels.com/photos/6311661/pexels-photo-6311661.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=800",
      category: "Bottom Wear",
      size: "L",
    },
    {
      id: 9,
      brand: "AUIND",
      name: "Trendy Overshirt",
      price: 1299,
      oldPrice: 2299,
      rating: 4.3,
      reviews: 390,
      img: "https://images.pexels.com/photos/1139743/pexels-photo-1139743.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=800",
      category: "Shirts",
      size: "XL",
    },
    {
      id: 10,
      brand: "HIGH&CO",
      name: "Printed Urban Tee",
      price: 699,
      oldPrice: 1299,
      rating: 4.0,
      reviews: 220,
      img: "https://images.pexels.com/photos/1524133/pexels-photo-1524133.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=800",
      category: "T-Shirts",
      size: "S",
    },
    {
      id: 11,
      brand: "UNITED",
      name: "Classic White Shirt",
      price: 899,
      oldPrice: 1699,
      rating: 4.2,
      reviews: 180,
      img: "https://images.pexels.com/photos/6311644/pexels-photo-6311644.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=800",
      category: "Shirts",
      size: "M",
    },
    {
      id: 12,
      brand: "AUIND",
      name: "Premium Black Jeans",
      price: 1299,
      oldPrice: 1999,
      rating: 4.6,
      reviews: 520,
      img: "https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=800",
      category: "Jeans",
      size: "L",
    },
  ];